<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Регистрация',
	'heading' => 'Отправка новой формы',
	'success_redirect' => 'congratulations.html',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'rw_@ukr.net',
		'to' => 'rw_@ukr.net'
	),
	'fields' => array(
		'custom_U914' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Имя:*',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Имя:*\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mail:*',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'E-mail:*\' не может быть пустым.',
				'format' => 'Поле \'E-mail:*\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U1036' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Телефон:*',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Телефон:*\' не может быть пустым.'
			)
		),
		'custom_U1048' => array(
			'order' => 4,
			'type' => 'checkbox',
			'label' => 'Мне есть 18 лет. Я ознакомился с
в СуперКопилке и полностью осознаю все риски,
cвязанные с участием*',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Мне есть 18 лет. Я ознакомился с
в СуперКопилке и полностью осознаю все риски,
cвязанные с участием*\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
